### ISSUE TITLE
Upgrade to one of the latest `Chromium` version for `Node.js 16.x`

### ISSUE THREAD

**Issue by x80486** [shivjm/docker-node-chromium-alpine#6]
I'm using this `Docker` image with `Puppeteer`. It's almost impossible to update `Puppeteer` if the browser version that's targeted it's not the same, or very similar.

Whenever you have some time free, would you be able to update the `Node.js` image to use one of the latest `Chromium` versions?

The latest one published is `node-chromium-alpine:node16-chromium102`.

**Comment by shivjm** [comment]
Thanks for the report. I’m not currently using this image anywhere, so it’s easy for me to miss things like this.

Unfortunately, I don’t think I can correct it easily, as Chromium is installed via the Alpine Linux package, and it looks like that’s both outdated and inconsistent in the base Node images:
```
❯❯ $command = "apk update -q && apk info chromium | head -n 1 | cut -d'-' -f 2"
❯❯ foreach ($v in @(14, 15, 16, 17, 18, 19)) { echo "node:$v-alpine: Chromium $(d run -it --rm --entrypoint ash node:$v-alpine -c `"$command`")" }
node:14-alpine: Chromium 102.0.5005.182
node:15-alpine: Chromium 81.0.4044.113
node:16-alpine: Chromium 102.0.5005.182
node:17-alpine: Chromium 99.0.4844.84
node:18-alpine: Chromium 102.0.5005.182
node:19-alpine: Chromium 102.0.5005.182
```
I believe the only way I could get the newest version on these platforms would be by installing it manually, in which case I’d also have to hard-code the version in the workflow and update it regularly. Let me think about whether there’s a better approach. (Suggestions welcome!)

**Comment by x80486** [comment]
Moving out from `Alpine` will make things easier. This `Dockerfile` should be enough:

```dockerfile
FROM docker.io/library/node:16-slim

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD="true"

# Install Google Chrome stable and required libraries/packages
RUN apt-get update; \
  apt-get --assume-yes install gnupg wget; \
  wget --quiet --output-document=- https://dl-ssl.google.com/linux/linux_signing_key.pub | gpg --dearmor > /etc/apt/trusted.gpg.d/google-archive.gpg; \
  sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'; \
  apt-get --assume-yes --no-install-recommends install google-chrome-stable; \
  rm -f -r /var/lib/apt/lists/*
```

The tagging might be different since you can only control the `Node.js` version, but all the libraries/packages to make `Chome` / `Chromium` work are installed by default. If someone wants a different version of `Chome` / `Chromium` it would be very easy to use the image and make it available withing his/her workflows.

> I took the example from different sources, including the `Puppeter` and `Buildkite` images.

**Comment by shivjm** [comment]
I’m sorry for taking so long to respond. Thank you for researching and suggesting alternatives; that was very helpful. I wanted to take some time to think about the available options.

> Moving out from Alpine will make things easier.

I’m hesitant to do this because it would change the environment, most obviously replacing Bash with ash, and increase the footprint of the images. However, I do agree that Chromium must be kept up-to-date. I’m considering creating separate `-debian` variants of the images that would include the latest version like you outlined. Alongside that, I’m looking into how feasible it is to similarly build Chrome from source on Alpine Linux. I might do both things.

For the moment, I noticed that a lot of the upstream images have seen updates:
```
node:14-alpine: Chromium 108.0.5359.125
node:15-alpine: Chromium 81.0.4044.113
node:16-alpine: Chromium 108.0.5359.125
node:17-alpine: Chromium 99.0.4844.84
node:18-alpine: Chromium 108.0.5359.125
node:19-alpine: Chromium 108.0.5359.125
```
Which means there’s, for example, a `node16-chromium108` tag. I know this is now an older version, but I hope it’s enough to tide you over until I can implement the changes I described.

**Comment by x80486** [comment]
It's OK...no worries. Do what you think it's best for the project. I'll adapt on my end.

**Comment by shivjm** [comment]
@x80486 I’ve added Debian variants based on your suggestion (after taking a silly amount of time to figure out the obvious solution). Note that I renamed the repositories on GH (shivjm/docker-node-chromium, this repository) and Docker Hub ([shivjm/node-chromium](https://hub.docker.com/r/shivjm/node-chromium)); the Debian variants have tags with a `-debian` suffix and the Alpine variants tags with a `-alpine` suffix. Thank you again for starting the discussion.

**Comment by x80486** [comment]
Thanks, @shivjm! :wave:

Let me give it a whirl sometime today or tomorrow. Will update here if anything weird happens.

**Comment by shivjm** [comment]
I’ll close this on the assumption that the original issue has been resolved. Please feel free to re-open it if not.
